local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("deDE", {
    ["Settings"] = "Einstellungen",
    ["General"] = "Allgemein",
    ["Borders"] = "Rahmen",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Symbole",
    ["Modules"] = "Module",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "Linksklick: Öffnen/Schließen",
    ["Right Click: Open/Close"] = "Rechtsklick: Öffnen/Schließen",

    ["Font settings"] = "Schrifteinstellungen",
    ["Font"] = "Schriftart",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Textstil",
    ["Disable"] = "Kein Effekt",
    ["Shadow"] = "Schatten",
    ["Outline"] = "Kontur",
    ["Thick outline"] = "Dicke Kontur",
    ["Stack count"] = "Stapelanzahl",
    ["Enable"] = "Aktivieren",
    ["Size"] = "Größe",
    ["Offset X"] = "Versatz X",
    ["Offset Y"] = "Versatz Y",
    ["Alignment"] = "Ausrichtung",
    ["Left"] = "Links",
    ["Center"] = "Mitte",
    ["Right"] = "Rechts",
    ["Text color"] = "Textfarbe",
    ["Minimap"] = "Minikarte",
    ["Hide minimap icon"] = "Minikartensymbol ausblenden",

    ["Border style"] = "Rahmenstil",
    ["Style selection"] = "Stilauswahl",
    ["Style 1"] = "Stil 1",
    ["Style 2"] = "Stil 2",
    ["Style 3"] = "Stil 3",
    ["Style 4"] = "Stil 4",
    ["Style 5"] = "Stil 5",
    ["Style 6"] = "Stil 6",
    ["Style 7"] = "Stil 7",
    ["Style settings"] = "Rahmeneinstellungen",
    ["Enable Border Glow"] = "Rahmenleuchten aktivieren",
    ["Border Style Scale"] = "Rahmenskalierung",
    ["Hover border on mouseover"] = "Rahmen beim Darüberfahren",
    ["Color selection"] = "Farbe des Hover-Rahmens",
    ["Additional settings"] = "Zusätzliche Einstellungen",
    ["Show borders from quality"] = "Mindestgegenstandsqualität für Rahmen",

    ["iLvl settings"] = "iLvl-Einstellungen",
    ["Font size"] = "Schriftgröße",
    ["Use item quality color"] = "Gegenstandsqualitätsfarbe verwenden",
    ["Show iLvl from quality"] = "Mindestgegenstandsqualität für iLvl",
    ["Quality"] = "Qualität",
    ["Poor"] = "Schlecht",
    ["Common"] = "Gewöhnlich",
    ["Uncommon"] = "Ungewöhnlich",
    ["Rare"] = "Selten",
    ["Epic"] = "Episch",

    ["Junk icon"] = "Schrottsymbol",
    ["Equipment upgrade icon"] = "Ausrüstungsupgrade-Symbol",
    ["Uncollected transmog icon"] = "Symbol für nicht gesammelte Transmog-Vorlage",
    ["Quest item icon"] = "Questgegenstand-Symbol",
    ["Missing enchant icon"] = "Symbol für fehlende Verzauberung",
    ["Only Character Frame and Inspect"] = "Nur Charakterfenster und Betrachten",

    ["* Modules in red are experimental"] = "* Rote Module sind experimentell",
    ["Character window"] = "Charakterfenster",
    ["Bags"] = "Taschen",
    ["Character bank"] = "Charakterbank",
    ["Warband bank"] = "Kriegsmeutenbank",
    ["Inspect"] = "Betrachten",
    ["Mail"] = "Post",
    ["Trade"] = "Handeln",
    ["Merchant"] = "Händler",
    ["Guild bank"] = "Gildenbank",
    ["Loot"] = "Beute",
    ["Quests"] = "Quests",
    ["Profession journal"] = "Berufejournal",
    ["Crafting orders"] = "Herstellungsaufträge",
})
