local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("enUS", {
    ["Settings"] = "Settings",
    ["General"] = "General",
    ["Borders"] = "Borders",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Icons",
    ["Modules"] = "Modules",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "Left Click: Open/Close",
    ["Right Click: Open/Close"] = "Right Click: Open/Close",

    ["Font settings"] = "Font settings",
    ["Font"] = "Font",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Text style",
    ["Disable"] = "No effect",
    ["Shadow"] = "Shadow",
    ["Outline"] = "Outline",
    ["Thick outline"] = "Thick outline",
    ["Stack count"] = "Stack count",
    ["Enable"] = "Enable",
    ["Size"] = "Size",
    ["Offset X"] = "Offset X",
    ["Offset Y"] = "Offset Y",
    ["Alignment"] = "Alignment",
    ["Left"] = "Left",
    ["Center"] = "Center",
    ["Right"] = "Right",
    ["Text color"] = "Text color",
    ["Minimap"] = "Minimap",
    ["Hide minimap icon"] = "Hide minimap icon",

    ["Border style"] = "Border style",
    ["Style selection"] = "Style selection",
    ["Style 1"] = "Style 1",
    ["Style 2"] = "Style 2",
    ["Style 3"] = "Style 3",
    ["Style 4"] = "Style 4",
    ["Style 5"] = "Style 5",
    ["Style 6"] = "Style 6",
    ["Style 7"] = "Style 7",
    ["Style settings"] = "Border settings",
    ["Enable Border Glow"] = "Enable border glow",
    ["Border Style Scale"] = "Border scale",
    ["Hover border on mouseover"] = "Hover border",
    ["Color selection"] = "Hover border color",
    ["Additional settings"] = "Additional settings",
    ["Show borders from quality"] = "Minimum item quality for borders",

    ["iLvl settings"] = "iLvl settings",
    ["Font size"] = "Font size",
    ["Use item quality color"] = "Use item quality color",
    ["Show iLvl from quality"] = "Minimum item quality for iLvl",
    ["Quality"] = "Quality",
    ["Poor"] = "Poor",
    ["Common"] = "Common",
    ["Uncommon"] = "Uncommon",
    ["Rare"] = "Rare",
    ["Epic"] = "Epic",

    ["Junk icon"] = "Junk icon",
    ["Equipment upgrade icon"] = "Equipment upgrade icon",
    ["Uncollected transmog icon"] = "Uncollected transmog icon",
    ["Quest item icon"] = "Quest item icon",
    ["Missing enchant icon"] = "Missing enchant icon",
    ["Only Character Frame and Inspect"] = "Only Character Frame and Inspect",

    ["* Modules in red are experimental"] = "* Modules in red are experimental",
    ["Character window"] = "Character window",
    ["Bags"] = "Bags",
    ["Character bank"] = "Character bank",
    ["Warband bank"] = "Warband bank",
    ["Inspect"] = "Inspect",
    ["Mail"] = "Mail",
    ["Trade"] = "Trade",
    ["Merchant"] = "Merchant",
    ["Guild bank"] = "Guild bank",
    ["Loot"] = "Loot",
    ["Quests"] = "Quests",
    ["Profession journal"] = "Profession journal",
    ["Crafting orders"] = "Crafting orders",
})
