local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("esES", {
    ["Settings"] = "Ajustes",
    ["General"] = "General",
    ["Borders"] = "Bordes",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Iconos",
    ["Modules"] = "Módulos",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "Clic izquierdo: abrir/cerrar",
    ["Right Click: Open/Close"] = "Clic derecho: abrir/cerrar",

    ["Font settings"] = "Ajustes de fuente",
    ["Font"] = "Fuente",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Estilo de texto",
    ["Disable"] = "Sin efecto",
    ["Shadow"] = "Sombra",
    ["Outline"] = "Contorno",
    ["Thick outline"] = "Contorno grueso",
    ["Stack count"] = "Cantidad de la pila",
    ["Enable"] = "Activar",
    ["Size"] = "Tamaño",
    ["Offset X"] = "Desplazamiento X",
    ["Offset Y"] = "Desplazamiento Y",
    ["Alignment"] = "Alineación",
    ["Left"] = "Izquierda",
    ["Center"] = "Centro",
    ["Right"] = "Derecha",
    ["Text color"] = "Color del texto",
    ["Minimap"] = "Minimapa",
    ["Hide minimap icon"] = "Ocultar icono del minimapa",

    ["Border style"] = "Estilo del borde",
    ["Style selection"] = "Selección de estilo",
    ["Style 1"] = "Estilo 1",
    ["Style 2"] = "Estilo 2",
    ["Style 3"] = "Estilo 3",
    ["Style 4"] = "Estilo 4",
    ["Style 5"] = "Estilo 5",
    ["Style 6"] = "Estilo 6",
    ["Style 7"] = "Estilo 7",
    ["Style settings"] = "Ajustes del borde",
    ["Enable Border Glow"] = "Activar brillo del borde",
    ["Border Style Scale"] = "Escala del borde",
    ["Hover border on mouseover"] = "Borde al pasar el ratón",
    ["Color selection"] = "Color del borde al pasar el ratón",
    ["Additional settings"] = "Ajustes adicionales",
    ["Show borders from quality"] = "Calidad mínima para mostrar bordes",

    ["iLvl settings"] = "Ajustes de iLvl",
    ["Font size"] = "Tamaño de fuente",
    ["Use item quality color"] = "Usar color de calidad del objeto",
    ["Show iLvl from quality"] = "Calidad mínima para mostrar iLvl",
    ["Quality"] = "Calidad",
    ["Poor"] = "Pobre",
    ["Common"] = "Común",
    ["Uncommon"] = "Poco común",
    ["Rare"] = "Raro",
    ["Epic"] = "Épico",

    ["Junk icon"] = "Icono de chatarra",
    ["Equipment upgrade icon"] = "Icono de mejora de equipo",
    ["Uncollected transmog icon"] = "Icono de transfiguración no obtenida",
    ["Quest item icon"] = "Icono de objeto de misión",
    ["Missing enchant icon"] = "Icono de encantamiento ausente",
    ["Only Character Frame and Inspect"] = "Solo ventana de personaje e Inspeccionar",

    ["* Modules in red are experimental"] = "* Los módulos en rojo son experimentales",
    ["Character window"] = "Ventana de personaje",
    ["Bags"] = "Bolsas",
    ["Character bank"] = "Banco del personaje",
    ["Warband bank"] = "Banco de banda guerrera",
    ["Inspect"] = "Inspeccionar",
    ["Mail"] = "Correo",
    ["Trade"] = "Comerciar",
    ["Merchant"] = "Mercader",
    ["Guild bank"] = "Banco de hermandad",
    ["Loot"] = "Botín",
    ["Quests"] = "Misiones",
    ["Profession journal"] = "Diario de profesiones",
    ["Crafting orders"] = "Pedidos de fabricación",
})
