local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("frFR", {
    ["Settings"] = "Paramètres",
    ["General"] = "Général",
    ["Borders"] = "Bordures",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Icônes",
    ["Modules"] = "Modules",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "Clic gauche : ouvrir/fermer",
    ["Right Click: Open/Close"] = "Clic droit : ouvrir/fermer",

    ["Font settings"] = "Paramètres de police",
    ["Font"] = "Police",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Style du texte",
    ["Disable"] = "Aucun effet",
    ["Shadow"] = "Ombre",
    ["Outline"] = "Contour",
    ["Thick outline"] = "Contour épais",
    ["Stack count"] = "Nombre dans la pile",
    ["Enable"] = "Activer",
    ["Size"] = "Taille",
    ["Offset X"] = "Décalage X",
    ["Offset Y"] = "Décalage Y",
    ["Alignment"] = "Alignement",
    ["Left"] = "Gauche",
    ["Center"] = "Centre",
    ["Right"] = "Droite",
    ["Text color"] = "Couleur du texte",
    ["Minimap"] = "Mini-carte",
    ["Hide minimap icon"] = "Masquer l’icône de la mini-carte",

    ["Border style"] = "Style de bordure",
    ["Style selection"] = "Sélection du style",
    ["Style 1"] = "Style 1",
    ["Style 2"] = "Style 2",
    ["Style 3"] = "Style 3",
    ["Style 4"] = "Style 4",
    ["Style 5"] = "Style 5",
    ["Style 6"] = "Style 6",
    ["Style 7"] = "Style 7",
    ["Style settings"] = "Paramètres de bordure",
    ["Enable Border Glow"] = "Activer la lueur de bordure",
    ["Border Style Scale"] = "Échelle de la bordure",
    ["Hover border on mouseover"] = "Bordure au survol",
    ["Color selection"] = "Couleur de la bordure au survol",
    ["Additional settings"] = "Paramètres supplémentaires",
    ["Show borders from quality"] = "Qualité minimale pour les bordures",

    ["iLvl settings"] = "Paramètres iLvl",
    ["Font size"] = "Taille de police",
    ["Use item quality color"] = "Utiliser la couleur de qualité de l’objet",
    ["Show iLvl from quality"] = "Qualité minimale pour iLvl",
    ["Quality"] = "Qualité",
    ["Poor"] = "Médiocre",
    ["Common"] = "Commun",
    ["Uncommon"] = "Inhabituel",
    ["Rare"] = "Rare",
    ["Epic"] = "Épique",

    ["Junk icon"] = "Icône de camelote",
    ["Equipment upgrade icon"] = "Icône d’amélioration d’équipement",
    ["Uncollected transmog icon"] = "Icône de transmogrification non collectée",
    ["Quest item icon"] = "Icône d’objet de quête",
    ["Missing enchant icon"] = "Icône d’enchantement manquant",
    ["Only Character Frame and Inspect"] = "Uniquement la fenêtre de personnage et Inspection",

    ["* Modules in red are experimental"] = "* Les modules en rouge sont expérimentaux",
    ["Character window"] = "Fenêtre de personnage",
    ["Bags"] = "Sacs",
    ["Character bank"] = "Banque du personnage",
    ["Warband bank"] = "Banque du bataillon",
    ["Inspect"] = "Inspection",
    ["Mail"] = "Courrier",
    ["Trade"] = "Échange",
    ["Merchant"] = "Marchand",
    ["Guild bank"] = "Banque de guilde",
    ["Loot"] = "Butin",
    ["Quests"] = "Quêtes",
    ["Profession journal"] = "Journal des métiers",
    ["Crafting orders"] = "Commandes d’artisanat",
})
