local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("itIT", {
    ["Settings"] = "Impostazioni",
    ["General"] = "Generale",
    ["Borders"] = "Bordi",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Icone",
    ["Modules"] = "Moduli",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "Clic sinistro: apri/chiudi",
    ["Right Click: Open/Close"] = "Clic destro: apri/chiudi",

    ["Font settings"] = "Impostazioni del carattere",
    ["Font"] = "Carattere",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Stile del testo",
    ["Disable"] = "Nessun effetto",
    ["Shadow"] = "Ombra",
    ["Outline"] = "Contorno",
    ["Thick outline"] = "Contorno spesso",
    ["Stack count"] = "Quantità della pila",
    ["Enable"] = "Abilita",
    ["Size"] = "Dimensione",
    ["Offset X"] = "Scostamento X",
    ["Offset Y"] = "Scostamento Y",
    ["Alignment"] = "Allineamento",
    ["Left"] = "Sinistra",
    ["Center"] = "Centro",
    ["Right"] = "Destra",
    ["Text color"] = "Colore del testo",
    ["Minimap"] = "Minimappa",
    ["Hide minimap icon"] = "Nascondi icona minimappa",

    ["Border style"] = "Stile del bordo",
    ["Style selection"] = "Selezione dello stile",
    ["Style 1"] = "Stile 1",
    ["Style 2"] = "Stile 2",
    ["Style 3"] = "Stile 3",
    ["Style 4"] = "Stile 4",
    ["Style 5"] = "Stile 5",
    ["Style 6"] = "Stile 6",
    ["Style 7"] = "Stile 7",
    ["Style settings"] = "Impostazioni del bordo",
    ["Enable Border Glow"] = "Abilita bagliore del bordo",
    ["Border Style Scale"] = "Scala del bordo",
    ["Hover border on mouseover"] = "Bordo al passaggio del mouse",
    ["Color selection"] = "Colore del bordo al passaggio del mouse",
    ["Additional settings"] = "Impostazioni aggiuntive",
    ["Show borders from quality"] = "Qualità minima per mostrare i bordi",

    ["iLvl settings"] = "Impostazioni iLvl",
    ["Font size"] = "Dimensione del carattere",
    ["Use item quality color"] = "Usa il colore della qualità dell’oggetto",
    ["Show iLvl from quality"] = "Qualità minima per mostrare iLvl",
    ["Quality"] = "Qualità",
    ["Poor"] = "Scadente",
    ["Common"] = "Comune",
    ["Uncommon"] = "Non comune",
    ["Rare"] = "Raro",
    ["Epic"] = "Epico",

    ["Junk icon"] = "Icona degli oggetti inutili",
    ["Equipment upgrade icon"] = "Icona miglioramento equipaggiamento",
    ["Uncollected transmog icon"] = "Icona trasmogrificazione non raccolta",
    ["Quest item icon"] = "Icona oggetto missione",
    ["Missing enchant icon"] = "Icona incantamento mancante",
    ["Only Character Frame and Inspect"] = "Solo finestra personaggio e Ispeziona",

    ["* Modules in red are experimental"] = "* I moduli in rosso sono sperimentali",
    ["Character window"] = "Finestra personaggio",
    ["Bags"] = "Borse",
    ["Character bank"] = "Banca del personaggio",
    ["Warband bank"] = "Banca della Brigata",
    ["Inspect"] = "Ispeziona",
    ["Mail"] = "Posta",
    ["Trade"] = "Scambio",
    ["Merchant"] = "Mercante",
    ["Guild bank"] = "Banca di gilda",
    ["Loot"] = "Bottino",
    ["Quests"] = "Missioni",
    ["Profession journal"] = "Diario delle professioni",
    ["Crafting orders"] = "Ordini di creazione",
})
