local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("koKR", {
    ["Settings"] = "설정",
    ["General"] = "일반",
    ["Borders"] = "테두리",
    ["iLvl"] = "iLvl",
    ["Icons"] = "아이콘",
    ["Modules"] = "모듈",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "왼쪽 클릭: 열기/닫기",
    ["Right Click: Open/Close"] = "오른쪽 클릭: 열기/닫기",

    ["Font settings"] = "글꼴 설정",
    ["Font"] = "글꼴",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "텍스트 스타일",
    ["Disable"] = "효과 없음",
    ["Shadow"] = "그림자",
    ["Outline"] = "외곽선",
    ["Thick outline"] = "두꺼운 외곽선",
    ["Stack count"] = "중첩 수량",
    ["Enable"] = "사용",
    ["Size"] = "크기",
    ["Offset X"] = "X 오프셋",
    ["Offset Y"] = "Y 오프셋",
    ["Alignment"] = "정렬",
    ["Left"] = "왼쪽",
    ["Center"] = "가운데",
    ["Right"] = "오른쪽",
    ["Text color"] = "텍스트 색상",
    ["Minimap"] = "미니맵",
    ["Hide minimap icon"] = "미니맵 아이콘 숨기기",

    ["Border style"] = "테두리 스타일",
    ["Style selection"] = "스타일 선택",
    ["Style 1"] = "스타일 1",
    ["Style 2"] = "스타일 2",
    ["Style 3"] = "스타일 3",
    ["Style 4"] = "스타일 4",
    ["Style 5"] = "스타일 5",
    ["Style 6"] = "스타일 6",
    ["Style 7"] = "스타일 7",
    ["Style settings"] = "테두리 설정",
    ["Enable Border Glow"] = "테두리 빛남 사용",
    ["Border Style Scale"] = "테두리 크기",
    ["Hover border on mouseover"] = "마우스오버 테두리",
    ["Color selection"] = "마우스오버 테두리 색상",
    ["Additional settings"] = "추가 설정",
    ["Show borders from quality"] = "테두리 표시 최소 아이템 품질",

    ["iLvl settings"] = "iLvl 설정",
    ["Font size"] = "글꼴 크기",
    ["Use item quality color"] = "아이템 품질 색상 사용",
    ["Show iLvl from quality"] = "iLvl 표시 최소 아이템 품질",
    ["Quality"] = "품질",
    ["Poor"] = "하급",
    ["Common"] = "일반",
    ["Uncommon"] = "고급",
    ["Rare"] = "희귀",
    ["Epic"] = "영웅",

    ["Junk icon"] = "잡동사니 아이콘",
    ["Equipment upgrade icon"] = "장비 업그레이드 아이콘",
    ["Uncollected transmog icon"] = "미수집 형상변환 아이콘",
    ["Quest item icon"] = "퀘스트 아이템 아이콘",
    ["Missing enchant icon"] = "마법부여 없음 아이콘",
    ["Only Character Frame and Inspect"] = "캐릭터 창과 살펴보기만",

    ["* Modules in red are experimental"] = "* 빨간색 모듈은 실험적입니다",
    ["Character window"] = "캐릭터 창",
    ["Bags"] = "가방",
    ["Character bank"] = "캐릭터 은행",
    ["Warband bank"] = "전투부대 은행",
    ["Inspect"] = "살펴보기",
    ["Mail"] = "우편",
    ["Trade"] = "거래",
    ["Merchant"] = "상인",
    ["Guild bank"] = "길드 은행",
    ["Loot"] = "전리품",
    ["Quests"] = "퀘스트",
    ["Profession journal"] = "전문기술 일지",
    ["Crafting orders"] = "제작 주문",
})
