local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("ptBR", {
    ["Settings"] = "Configurações",
    ["General"] = "Geral",
    ["Borders"] = "Bordas",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Ícones",
    ["Modules"] = "Módulos",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "Clique esquerdo: abrir/fechar",
    ["Right Click: Open/Close"] = "Clique direito: abrir/fechar",

    ["Font settings"] = "Configurações de fonte",
    ["Font"] = "Fonte",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Estilo do texto",
    ["Disable"] = "Sem efeito",
    ["Shadow"] = "Sombra",
    ["Outline"] = "Contorno",
    ["Thick outline"] = "Contorno espesso",
    ["Stack count"] = "Quantidade do conjunto",
    ["Enable"] = "Ativar",
    ["Size"] = "Tamanho",
    ["Offset X"] = "Deslocamento X",
    ["Offset Y"] = "Deslocamento Y",
    ["Alignment"] = "Alinhamento",
    ["Left"] = "Esquerda",
    ["Center"] = "Centro",
    ["Right"] = "Direita",
    ["Text color"] = "Cor do texto",
    ["Minimap"] = "Minimapa",
    ["Hide minimap icon"] = "Ocultar ícone do minimapa",

    ["Border style"] = "Estilo da borda",
    ["Style selection"] = "Seleção de estilo",
    ["Style 1"] = "Estilo 1",
    ["Style 2"] = "Estilo 2",
    ["Style 3"] = "Estilo 3",
    ["Style 4"] = "Estilo 4",
    ["Style 5"] = "Estilo 5",
    ["Style 6"] = "Estilo 6",
    ["Style 7"] = "Estilo 7",
    ["Style settings"] = "Configurações da borda",
    ["Enable Border Glow"] = "Ativar brilho da borda",
    ["Border Style Scale"] = "Escala da borda",
    ["Hover border on mouseover"] = "Borda ao passar o mouse",
    ["Color selection"] = "Cor da borda ao passar o mouse",
    ["Additional settings"] = "Configurações adicionais",
    ["Show borders from quality"] = "Qualidade mínima para mostrar bordas",

    ["iLvl settings"] = "Configurações de iLvl",
    ["Font size"] = "Tamanho da fonte",
    ["Use item quality color"] = "Usar cor da qualidade do item",
    ["Show iLvl from quality"] = "Qualidade mínima para mostrar iLvl",
    ["Quality"] = "Qualidade",
    ["Poor"] = "Ruim",
    ["Common"] = "Comum",
    ["Uncommon"] = "Incomum",
    ["Rare"] = "Raro",
    ["Epic"] = "Épico",

    ["Junk icon"] = "Ícone de sucata",
    ["Equipment upgrade icon"] = "Ícone de melhoria de equipamento",
    ["Uncollected transmog icon"] = "Ícone de transmog não coletado",
    ["Quest item icon"] = "Ícone de item de missão",
    ["Missing enchant icon"] = "Ícone de encantamento ausente",
    ["Only Character Frame and Inspect"] = "Somente janela do personagem e Inspecionar",

    ["* Modules in red are experimental"] = "* Módulos em vermelho são experimentais",
    ["Character window"] = "Janela do personagem",
    ["Bags"] = "Bolsas",
    ["Character bank"] = "Banco do personagem",
    ["Warband bank"] = "Banco do Bando Guerreiro",
    ["Inspect"] = "Inspecionar",
    ["Mail"] = "Correio",
    ["Trade"] = "Troca",
    ["Merchant"] = "Mercador",
    ["Guild bank"] = "Banco da guilda",
    ["Loot"] = "Saque",
    ["Quests"] = "Missões",
    ["Profession journal"] = "Diário de profissões",
    ["Crafting orders"] = "Encomendas de criação",
})
