local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("ruRU", {
    ["Settings"] = "Настройки",
    ["General"] = "Общее",
    ["Borders"] = "Рамки",
    ["iLvl"] = "iLvl",
    ["Icons"] = "Иконки",
    ["Modules"] = "Модули",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "ЛКМ: Открыть/закрыть",
    ["Right Click: Open/Close"] = "ПКМ: Открыть/закрыть",

    ["Font settings"] = "Настройки шрифта",
    ["Font"] = "Шрифт",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "Стиль текста",
    ["Disable"] = "Без эффекта",
    ["Shadow"] = "Тень",
    ["Outline"] = "Контур",
    ["Thick outline"] = "Толстый контур",
    ["Stack count"] = "Количество в стопке",
    ["Enable"] = "Включить",
    ["Size"] = "Размер",
    ["Offset X"] = "Смещение X",
    ["Offset Y"] = "Смещение Y",
    ["Alignment"] = "Выравнивание",
    ["Left"] = "Слева",
    ["Center"] = "По центру",
    ["Right"] = "Справа",
    ["Text color"] = "Цвет текста",
    ["Minimap"] = "Мини-карта",
    ["Hide minimap icon"] = "Скрывать иконку у мини-карты",

    ["Border style"] = "Стиль рамки",
    ["Style selection"] = "Выбор стиля",
    ["Style 1"] = "Стиль 1",
    ["Style 2"] = "Стиль 2",
    ["Style 3"] = "Стиль 3",
    ["Style 4"] = "Стиль 4",
    ["Style 5"] = "Стиль 5",
    ["Style 6"] = "Стиль 6",
    ["Style 7"] = "Стиль 7",
    ["Style settings"] = "Параметры рамки",
    ["Enable Border Glow"] = "Включить свечение рамки",
    ["Border Style Scale"] = "Масштаб рамки",
    ["Hover border on mouseover"] = "Рамка при наведении",
    ["Color selection"] = "Цвет рамки при наведении",
    ["Additional settings"] = "Дополнительно",
    ["Show borders from quality"] = "Минимальное качество для рамки",

    ["iLvl settings"] = "Настройки iLvl",
    ["Font size"] = "Размер шрифта",
    ["Use item quality color"] = "Окрашивать по качеству предмета",
    ["Show iLvl from quality"] = "Минимальное качество для iLvl",
    ["Quality"] = "Качество",
    ["Poor"] = "Низкое",
    ["Common"] = "Обычное",
    ["Uncommon"] = "Необычное",
    ["Rare"] = "Редкое",
    ["Epic"] = "Эпическое",

    ["Junk icon"] = "Иконка хлама",
    ["Equipment upgrade icon"] = "Иконка улучшения экипировки",
    ["Uncollected transmog icon"] = "Иконка несобранного трансмога",
    ["Quest item icon"] = "Иконка предмета задания",
    ["Missing enchant icon"] = "Иконка без энчанта",
    ["Only Character Frame and Inspect"] = "Только Character Frame и Inspect",

    ["* Modules in red are experimental"] = "* Красным отмечены тестовые модули",
    ["Character window"] = "Окно персонажа",
    ["Bags"] = "Сумки",
    ["Character bank"] = "Банк персонажа",
    ["Warband bank"] = "Банк отряда",
    ["Inspect"] = "Осмотр",
    ["Mail"] = "Почта",
    ["Trade"] = "Обмен",
    ["Merchant"] = "Торговец",
    ["Guild bank"] = "Банк гильдии",
    ["Loot"] = "Добыча",
    ["Quests"] = "Задания",
    ["Profession journal"] = "Журнал профессий",
    ["Crafting orders"] = "Заказы на изготовление",
})
