local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("zhCN", {
    ["Settings"] = "设置",
    ["General"] = "通用",
    ["Borders"] = "边框",
    ["iLvl"] = "iLvl",
    ["Icons"] = "图标",
    ["Modules"] = "模块",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "左键：打开/关闭",
    ["Right Click: Open/Close"] = "右键：打开/关闭",

    ["Font settings"] = "字体设置",
    ["Font"] = "字体",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "文字样式",
    ["Disable"] = "无效果",
    ["Shadow"] = "阴影",
    ["Outline"] = "描边",
    ["Thick outline"] = "粗描边",
    ["Stack count"] = "堆叠数量",
    ["Enable"] = "启用",
    ["Size"] = "大小",
    ["Offset X"] = "X 偏移",
    ["Offset Y"] = "Y 偏移",
    ["Alignment"] = "对齐",
    ["Left"] = "左",
    ["Center"] = "居中",
    ["Right"] = "右",
    ["Text color"] = "文字颜色",
    ["Minimap"] = "小地图",
    ["Hide minimap icon"] = "隐藏小地图图标",

    ["Border style"] = "边框样式",
    ["Style selection"] = "样式选择",
    ["Style 1"] = "样式 1",
    ["Style 2"] = "样式 2",
    ["Style 3"] = "样式 3",
    ["Style 4"] = "样式 4",
    ["Style 5"] = "样式 5",
    ["Style 6"] = "样式 6",
    ["Style 7"] = "样式 7",
    ["Style settings"] = "边框设置",
    ["Enable Border Glow"] = "启用边框发光",
    ["Border Style Scale"] = "边框缩放",
    ["Hover border on mouseover"] = "鼠标悬停边框",
    ["Color selection"] = "悬停边框颜色",
    ["Additional settings"] = "附加设置",
    ["Show borders from quality"] = "显示边框的最低物品品质",

    ["iLvl settings"] = "iLvl 设置",
    ["Font size"] = "字体大小",
    ["Use item quality color"] = "使用物品品质颜色",
    ["Show iLvl from quality"] = "显示 iLvl 的最低物品品质",
    ["Quality"] = "品质",
    ["Poor"] = "粗糙",
    ["Common"] = "普通",
    ["Uncommon"] = "优秀",
    ["Rare"] = "精良",
    ["Epic"] = "史诗",

    ["Junk icon"] = "垃圾图标",
    ["Equipment upgrade icon"] = "装备升级图标",
    ["Uncollected transmog icon"] = "未收集幻化图标",
    ["Quest item icon"] = "任务物品图标",
    ["Missing enchant icon"] = "缺少附魔图标",
    ["Only Character Frame and Inspect"] = "仅角色窗口和观察",

    ["* Modules in red are experimental"] = "* 红色模块为实验性功能",
    ["Character window"] = "角色窗口",
    ["Bags"] = "背包",
    ["Character bank"] = "角色银行",
    ["Warband bank"] = "战团银行",
    ["Inspect"] = "观察",
    ["Mail"] = "邮件",
    ["Trade"] = "交易",
    ["Merchant"] = "商人",
    ["Guild bank"] = "公会银行",
    ["Loot"] = "拾取",
    ["Quests"] = "任务",
    ["Profession journal"] = "专业日志",
    ["Crafting orders"] = "制造订单",
})
