local _, NS = ...
if not NS or not NS.AddLocale then return end

NS.AddLocale("zhTW", {
    ["Settings"] = "設定",
    ["General"] = "一般",
    ["Borders"] = "邊框",
    ["iLvl"] = "iLvl",
    ["Icons"] = "圖示",
    ["Modules"] = "模組",
    ["BlizzItemGlowFix"] = "BlizzItemGlowFix",
    ["Left Click: Open/Close"] = "左鍵：開啟/關閉",
    ["Right Click: Open/Close"] = "右鍵：開啟/關閉",

    ["Font settings"] = "字型設定",
    ["Font"] = "字型",
    ["Roboto Condensed Bold"] = "Roboto Condensed Bold",
    ["Style"] = "文字樣式",
    ["Disable"] = "無效果",
    ["Shadow"] = "陰影",
    ["Outline"] = "外框",
    ["Thick outline"] = "粗外框",
    ["Stack count"] = "堆疊數量",
    ["Enable"] = "啟用",
    ["Size"] = "大小",
    ["Offset X"] = "X 偏移",
    ["Offset Y"] = "Y 偏移",
    ["Alignment"] = "對齊",
    ["Left"] = "左",
    ["Center"] = "置中",
    ["Right"] = "右",
    ["Text color"] = "文字顏色",
    ["Minimap"] = "小地圖",
    ["Hide minimap icon"] = "隱藏小地圖圖示",

    ["Border style"] = "邊框樣式",
    ["Style selection"] = "樣式選擇",
    ["Style 1"] = "樣式 1",
    ["Style 2"] = "樣式 2",
    ["Style 3"] = "樣式 3",
    ["Style 4"] = "樣式 4",
    ["Style 5"] = "樣式 5",
    ["Style 6"] = "樣式 6",
    ["Style 7"] = "樣式 7",
    ["Style settings"] = "邊框設定",
    ["Enable Border Glow"] = "啟用邊框發光",
    ["Border Style Scale"] = "邊框縮放",
    ["Hover border on mouseover"] = "滑鼠指向邊框",
    ["Color selection"] = "滑鼠指向邊框顏色",
    ["Additional settings"] = "額外設定",
    ["Show borders from quality"] = "顯示邊框的最低物品品質",

    ["iLvl settings"] = "iLvl 設定",
    ["Font size"] = "字型大小",
    ["Use item quality color"] = "使用物品品質顏色",
    ["Show iLvl from quality"] = "顯示 iLvl 的最低物品品質",
    ["Quality"] = "品質",
    ["Poor"] = "粗糙",
    ["Common"] = "普通",
    ["Uncommon"] = "優秀",
    ["Rare"] = "精良",
    ["Epic"] = "史詩",

    ["Junk icon"] = "垃圾圖示",
    ["Equipment upgrade icon"] = "裝備升級圖示",
    ["Uncollected transmog icon"] = "未收集塑形圖示",
    ["Quest item icon"] = "任務物品圖示",
    ["Missing enchant icon"] = "缺少附魔圖示",
    ["Only Character Frame and Inspect"] = "僅角色視窗和觀察",

    ["* Modules in red are experimental"] = "* 紅色模組為實驗性功能",
    ["Character window"] = "角色視窗",
    ["Bags"] = "背包",
    ["Character bank"] = "角色銀行",
    ["Warband bank"] = "戰隊銀行",
    ["Inspect"] = "觀察",
    ["Mail"] = "郵件",
    ["Trade"] = "交易",
    ["Merchant"] = "商人",
    ["Guild bank"] = "公會銀行",
    ["Loot"] = "拾取",
    ["Quests"] = "任務",
    ["Profession journal"] = "專業技能日誌",
    ["Crafting orders"] = "製造訂單",
})
